name: Deploy to EC2

on:
    push:
        branches:
            -main

jobs:
    deploy:
        runs-on: ubuntu-lastest

        steps: 
            - name: SSH into EC2 and execue commands
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_PRIVATE_KEY }}
                
